### PR TITLE
Add a variable 'gradualOpacity' to handle Opacity over time

### PR DESCRIPTION
**Pull request by baeksj**
Implemented with the same opacity functionality provided by Home Assistant's default map-card.

Example config>
```
entities:
  - entity: device_tracker.baeksj_s23
    display: icon
    gradualOpacity: 0.8 #This variable can be set to a value less than or equal to 1.
```

### CODE REVIEW

**Comment by nathan-gs** [comment]
Very nice! This solves #73 

Can you also update the README?

**Comment by ildar170975** [comment]
Very nice feature. Looking forward to see a description of the newly added option.

**Comment by baeksj** [comment]
I have added a detailed description of the newly added gradualOpacity option to the README.md. 
Thank you!

**Review by nathan-gs — APPROVED** [review]

**Comment by nathan-gs** [comment]
@baeksj to make the naming a bit more consistent I renamed `gradualOpacity` to `gradual_opacity`.

**Comment by baeksj** [comment]
> @baeksj to make the naming a bit more consistent I renamed `gradualOpacity` to `gradual_opacity`.

Very good. Of course, that's the right thing to do. 
Many people in Korea use this card because we can change its map source. 
Thank you for your effort.

**Pull request merged**
