### PR TITLE
Add 'Reset focus' button on the map and more

### PR DESCRIPTION
**Pull request by baeksj**
1. Add 'Reset focus' button on the map.
2. 'focus_on_fit' - when adding entities such as zones, there may be cases where you want to exclude these entities from the fit map target.
3. 'z_index_offset' - Determine which entity marker to display first when they overlap.
4. Set padding value to 0.1. fix the issue of entities being too close to the edges.
5. Lexical fix for gradualOpacity in README.md.

### CODE REVIEW

**Comment by nathan-gs** [comment]
@baeksj looks good! However it's missing the README updates.

Thx!

**Comment by baeksj** [comment]
> Unfortunately the z_index_offset does not do what it should do on my end. I see leaflet still generates another offset.

The z_index_offset is an option provided by Leaflet. Based on my testing, it seems to work as intended only when a sufficiently large value is input. If you set values of 100 or more for each entity, it should behave as expected.
I don't know why it behaves this way either.

**Comment by baeksj** [comment]
> @baeksj looks good! However it's missing the README updates.
> 
> Thx!

I forgot to add the modified README. I have now added it.

**Review by nathan-gs — APPROVED** [review]

**Comment by nathan-gs** [comment]
Thank you for the PR @baeksj!

**Comment by nathan-gs** [comment]
Available in [v1.6.0](https://github.com/nathan-gs/ha-map-card/releases/tag/v1.6.0), thank you again @baeksj!!!

**Pull request merged**
