### PR TITLE
History for WMS & TileLayers

### PR DESCRIPTION
**Pull request by thybag**
Allows WMS/Tile layers to have their time/date driven by the date picker or an external entity as with entity history.

* Setting `history` on WMS/Tile layer will link it to history mechanism set at map level. This supports specific date/times, entity driven date times and date picker date times. Will use the start point of any time ranges.
* Works for both WMS and Tile layers
* None date linked WMS and Tile layers still work as before.
* WMS/Layer history supports sub properties `source` to set custom entity or date to use for layer. `suffix` can also be set on source as with other history properties. 
* Additional flag on layers to `force_midnight` as some WMS/Maps only return results if date is at midnight e.g. https://geo.irceline.be/rioifdm/wms

Simple example with WMS driven by date_section date range picker
```
type: custom:map-card
history_date_selection: true
entities:
  - zone.home
wms:
  - url: https://geo.irceline.be/rioifdm/wms
    history: time
    options:
      layers: pm25_hmean
      transparent: true
      format: image/png
      opacity: 0.7
      tiled: true
      attribution: <a href="https://www.irceline.be/">IRCELINE</a>
```

More advanced example with tile_layer
```
type: custom:map-card
history_date_selection: false
entities:
  - zone.home
tile_layers:
  url: >-
    https://wmts.marine.copernicus.eu/teroWmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=&LAYER={layer}&STYLE=&FORMAT=image/png&TILEMATRIXSET={tileMatrixSet}&TILEMATRIX={z}&time={time}&TILEROW={y}&TILECOL={x}
  history:
    property: time
    source: input_number.test_number_value
    suffix: months ago
  options:
    layer: >-
      GLOBAL_MULTIYEAR_WAV_001_032/cmems_mod_glo_wav_my_0.2deg_PT3H-i_202311/VHM0
    tileMatrixSet: EPSG:4326
    noWrap: true

```

Work todo
- [x] Refactor a little. Tilelayers can likely reuse same code for extra logic. Need to fine example tile layer to test with.
- [x] Check `source` entity works as expected.
- [x] Add source_suffix
- [x] Update readme with instructions on how to use it.
- [x] Wrap suffix logic into a util as is now repeated in 3/4 places

Fixes https://github.com/nathan-gs/ha-map-card/issues/44

### CODE REVIEW

**Comment by thybag** [comment]
Hi @nathan-gs, I think this should now be good to review.
Unsure if the CI issues are anything i need to take note of / address as part of this PR.

The WMS/Layer history feature should support everything the map and entity level ones do, with the addition of needing to set the attribute being used as this could be time/date or something else in theory, as well as a flag to force midnight on dates (days ago uses current time for example so won't work correctly with some WMS/Tile layers if using that to drive them).

I've also now allowed single WMS/Tile layers to be set, rather than them needing to be a lits.

Readme should be updated, so hopefully the added docs all make sense.

Cheers,
Carl

**Comment by nathan-gs** [comment]
@thybag not sure why the HACS validation flow keep running, would you mind testing (it's hard to test for me)

**Comment by nathan-gs** [comment]
If you pull from main, normally the test failures should disappear.

**Comment by thybag** [comment]
Looks like that sorted it 👍

**Review by nathan-gs — APPROVED** [review]

**Comment by nathan-gs** [comment]
Thank you @thybag for this very cool addition, available in [v1.2.0](https://github.com/nathan-gs/ha-map-card/releases/tag/v1.2.0)

**Pull request merged**
